#!/usr/bin/env bash
set -euo pipefail


# -------------------------------
# Check if build directory
# -------------------------------
if [ ! -d "build" ]; then 
	mkdir build
fi

cd build

# -------------------------------
# build_script: Build Barrage (barr)
# -------------------------------
cmake -G Ninja ..
ninja

