#!/usr/bin/env bash
set -euo pipefail


# -------------------------------
# Check if build directory
# -------------------------------
if [ ! -d "build" ]; then 
	mkdir build
fi

cd build

# -------------------------------
# Build Build Barrage (barr)
# -------------------------------
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
ninja


