#ifndef ATL_GLOB_CONFIG_KEYS_H_
#define ATL_GLOB_CONFIG_KEYS_H_

#define ATL_GLOB_CONFIG_KEY_ROOT_DIR "ATL_GLOB_CONFIG_ROOT_DIR"
#define ATL_GLOB_CONFIG_KEY_DATA_DIR "ATL_GLOB_CONFIG_DATA_DIR"

#define ATL_GLOB_CONFIG_KEY_COMPILER "ATL_GLOB_CONFIG_COMPILER"
#define ATL_GLOB_CONFIG_KEY_LINKER "ATL_GLOB_CONFIG_LINKER"

#define ATL_GLOB_CONFIG_KEY_CFLAGS "ATL_GLOB_CONFIG_CFLAGS"

#endif  // ATL_GLOB_CONFIG_KEYS_H_
