#ifndef BARR_GLOB_CONFIG_KEYS_H_
#define BARR_GLOB_CONFIG_KEYS_H_

#define BARR_GLOB_CONFIG_KEY_ROOT_DIR "BARR_GLOB_CONFIG_ROOT_DIR"
#define BARR_GLOB_CONFIG_KEY_DATA_DIR "BARR_GLOB_CONFIG_DATA_DIR"

#define BARR_GLOB_CONFIG_KEY_COMPILER "BARR_GLOB_CONFIG_COMPILER"
#define BARR_GLOB_CONFIG_KEY_LINKER "BARR_GLOB_CONFIG_LINKER"

#define BARR_GLOB_CONFIG_KEY_CFLAGS "BARR_GLOB_CONFIG_CFLAGS"

#endif  // BARR_GLOB_CONFIG_KEYS_H_
