#ifndef OLMOS_VARIABLES_H_
#define OLMOS_VARIABLES_H_

#define OLM_VAR_COMPILER "COMPILER"
#define OLM_VAR_LINKER "LINKER"
#define OLM_VAR_TARGET "TARGET"
#define OLM_VAR_TARGET_TYPE "TARGET_TYPE"
#define OLM_VAR_BUILD_TYPE "BUILD_TYPE"
#define OLM_VAR_MAIN_SOURCE "MAIN_SOURCE"
#define OLM_VAR_CFLAGS "CFLAGS"
#define OLM_VAR_CFLAGS_RELEASE "CFLAGS_RELEASE"
#define OLM_VAR_GLOB_SOURCES "GLOB_SOURCES"
#define OLM_VAR_SOURCES "SOURCES"
#define OLM_VAR_INCLUDES "INCLUDES"
#define OLM_VAR_AUTO_INC_DISCOVERY "AUTO_INCLUDE_DISCOVERY"
#define OLM_VAR_DEFINES "DEFINES"
#define OLM_VAR_GEN_CCMDS "GEN_COMPILE_COMMANDS"
#define OLM_VAR_LIB_PATHS "LIB_PATHS"
#define OLM_VAR_LINKER_FLAGS "LFLAGS"
#define OLM_VAR_OUT_DIR "OUT_DIR"
#define OLM_VAR_BIN_OUT_PATH "BINARY_OUT_PATH"
#define OLM_VAR_EXCLUDE_PATTERNS "EXCLUDE_PATTERNS"
#define OLM_VAR_VERSION "VERSION"
#define OLM_VAR_CLEAN_TARGETS "CLEAN_TARGETS"
#define OLM_VAR_MODULE_INCLUDES "MODULES_INCLUDES"

#endif  // OLMOS_VARIABLES_H_
